local sharedItems = exports['qbr-core']:GetItems()

-- RegisterServerEvent('check_Key1')
-- AddEventHandler('check_Key1',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val1')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("open_chambre1", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)
-- RegisterServerEvent('close_Key1')
-- AddEventHandler('close_Key1',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val1')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("close_chambre1", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)		
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)

-- RegisterServerEvent('check_Key2')
-- AddEventHandler('check_Key2',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val2')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("open_chambre2", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)
-- RegisterServerEvent('close_Key2')
-- AddEventHandler('close_Key2',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val2')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("close_chambre2", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)		
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)


-- RegisterServerEvent('check_Key3')
-- AddEventHandler('check_Key3',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val3')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("open_chambre3", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)

-- RegisterServerEvent('close_Key3')
-- AddEventHandler('close_Key3',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val3')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("close_chambre3", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)		
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)

-- RegisterServerEvent('check_Key4')
-- AddEventHandler('check_Key4',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val4')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("open_chambre4", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)
-- RegisterServerEvent('close_Key4')
-- AddEventHandler('close_Key4',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val4')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("close_chambre4", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)		
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)

-- RegisterServerEvent('check_Key5')
-- AddEventHandler('check_Key5',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val5')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("open_chambre5", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)
-- RegisterServerEvent('close_Key5')
-- AddEventHandler('close_Key5',function()
-- 	local src = source
--     local Player = exports['qbr-core']:GetPlayer(src)
-- 	local key = Player.Functions.GetItemByName('val5')
-- 	local pass = Player.Functions.GetItemByName('multipass')
-- 	if Player.PlayerData.items ~= nil then
-- 	if key ~= nil or pass ~= nil  then		
-- 		TriggerClientEvent("close_chambre5", source)
-- 	else
-- 		TriggerClientEvent("no_key", source)		
-- 	end
-- 	else
-- 		TriggerClientEvent("no_key", source)
-- 	end
-- end)